* rzmq-enhancement

  The ffi-rzmq wraps ZeroMQ nicely, but not in a Ruby-friendly manner.
  here, we take that one step further to present a more Ruby-friendy
  interface.

** Preliminaries
   
   This is implemented as a DSLish Ruby-friendly interface. The
   initial implementation shall be as "lean" as possible, basically
   serving our needs at Sensorberg. Eventually, we'll flesh this 
   out to fully support most of the ffi-rzmq interface.

** Install
   
   Make sure the ZeroMQ library is already installed on your system. If you
   are on a Mac, we recommend 'brew' or 'macports' to get it.
   
   From command-line:
   #+begin_src bash
   gem install rzmq-enhancement
   #+end_src

   Or in you Gemfile:
   #+begin_src ruby
   gem 'rzmq-enhancement'
   #+end_src

** Contributing to rzmq-enhancement
 
   - Check out the latest master to make sure the feature hasn't been implemented or the bug hasn't been fixed yet.
   - Check out the issue tracker to make sure someone already hasn't requested it and/or contributed it.
   - Fork the project.
   - Start a feature/bugfix branch.
   - Commit and push until you are happy with your contribution.
   - Make sure to add tests for it. This is important so I don't break it in a future version unintentionally.
   - Please try not to mess with the Rakefile, version, or history. If you want to have your own version, or is otherwise necessary, that is fine, but please isolate to its own commit so I can cherry-pick around it.

** Copyright

   Copyright (c) 2017 Fred Mitchell and Sensorberg GbmH. See LICENSE.txt for
   further details.
